name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:             
  pull_request:
    branches: [ "master" ]
    
env:
  REPO_TAG: ghcr.io/xamma/tabula:latest

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build . --file Dockerfile --no-cache --tag ${{ env.REPO_TAG }}

      - name: Push Docker image
        run: docker push ${{ env.REPO_TAG }}